version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    restart: unless-stopped
    command:
      - "--log.level=ERROR"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dnsovertls.address=:853"
      - "--entrypoints.dns.address=:53"
      - "--entrypoints.udpdns.address=:53/udp"
      - "--entrypoints.web.address=:80"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=ian@ianmyjer.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    networks:
      - traefik_default
    ports:
      - "10.0.0.200:443:443"
      - "10.0.0.200:853:853"
      - "10.0.0.200:53:53"
      - "10.0.0.200:53:53/udp"
      - "10.0.0.200:80:80"
      - "10.0.0.200:8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  traefik_default:
    external: true

volumes:
  letsencrypt:

